# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daaa198befcd3bff02beb9040dd1b3692ba852568d60d277afb3706f10a10189003cf599c0cf60453ca40932a98fb52165d4fbaab6ab98d2e597ce513fd09c26

test:
  secret_key_base: ced9ddb8e1229a4ce391fbe0a1cb48fcd1721fe6c83e8e332e303d3b25b1900ea47d5d084b8564803037cd5b44962127676ef73ca269dff23a08a97b930f8477

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
